# BEGIN_KITTY_THEME
# Jet Brains Darcula
include current-theme.conf
# END_KITTY_THEME

background_opacity 0.9
background_blur 32

font_size 9.0
font_family 	 JetBrainsMono NFM Regular
bold_font 	 JetBrainsMono NFM Bold
italic_font 	 JetBrainsMono NFM Italic
bold_italic_font JetBrainsMono NFM Bold Italic

#Make letters a bit closer to each other
modify_font cell_width 95%

#Make kitty borderless
#'yes' disbles round corners and title bar
#'titlebar-only' disables title bar
hide_window_decorations titlebar-only

window_padding_width 1
window_margin_width 1

#Draw only borders that separate window from neighbor
draw_minimal_border yea

placement_strategy center

#Changes multi-character ligatures
# options: always, never, cursor (don't render when cursor is over them)
disable_ligatures cursor

#Change cursor shape possible: block, beam, underline
cursor_shape block

#Color and style of URL uinder mouse
#possible styles: none, curly, straight, double, dotted, dashed
url_color #0078bd
url_style curly
